parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: null
    database_user: root
    database_password: null
    mailer_transport: gmail
    mailer_encryption: ssl
    mailer_auth_mode: login
    mailer_host: smtp.gmail.com
    mailer_user: rojo.angel
    mailer_password: your_password
    locale: en
    secret: 27b46ad1cbf5a1f3d4ce310c880b1d8ee
    database_path: null
