doctrine:
    orm:
        entity_managers:
            default: # that's the name of the entity manager
    dbal:
        default_connection:   default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
parameters:
    # Blogger contact email address
    blogger_blog.emails.contact_email: contact@email.com